// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTqh1Dw1bQJ0lH_QlcSFn5eflnee_ZTCw',
    appId: '1:987260328263:web:cfaff4e4bbca4bdac65462',
    messagingSenderId: '987260328263',
    projectId: 'bd-jobs-a84c7',
    authDomain: 'bd-jobs-a84c7.firebaseapp.com',
    storageBucket: 'bd-jobs-a84c7.appspot.com',
    measurementId: 'G-N69Q0EZTKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8WxFSI-UJ3_ijWWe9EFNNvramswH2cKs',
    appId: '1:987260328263:android:bb3c231b35a321bbc65462',
    messagingSenderId: '987260328263',
    projectId: 'bd-jobs-a84c7',
    storageBucket: 'bd-jobs-a84c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArAjxY-M1jzEIDLJKFiTUmE7DmcilGros',
    appId: '1:987260328263:ios:90146d256f582dc3c65462',
    messagingSenderId: '987260328263',
    projectId: 'bd-jobs-a84c7',
    storageBucket: 'bd-jobs-a84c7.appspot.com',
    androidClientId: '987260328263-kq5v2d6u9thbgd4urt8hbb3ejb9l96ea.apps.googleusercontent.com',
    iosClientId: '987260328263-bep9u62fo439kgj6jg6irssobhmvphpt.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobSearch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArAjxY-M1jzEIDLJKFiTUmE7DmcilGros',
    appId: '1:987260328263:ios:e24b030e0f70ff3bc65462',
    messagingSenderId: '987260328263',
    projectId: 'bd-jobs-a84c7',
    storageBucket: 'bd-jobs-a84c7.appspot.com',
    androidClientId: '987260328263-kq5v2d6u9thbgd4urt8hbb3ejb9l96ea.apps.googleusercontent.com',
    iosClientId: '987260328263-qp0gb9tl48iuh7nohfgocrsn18dk23fl.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobSearch.RunnerTests',
  );
}
